[package]
name = "instructions"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.15", features = ["csr"] }
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = ["CanvasRenderingContext2d"] }
